version: '3.6'
services:
  springy:
    build:
      context: .
    ports:
      - "9999"
      - "7091"
    environment:
      - LAUNCH_TYPE=local
      - AWS_PROFILE=default
      - ENVIRONMENT_NAME=dev
    volumes:
      - ~/.aws:${HOME}/.aws
    entrypoint: ./init-and-run.sh local dev
