server:
  port: 9999
  http2:
    enabled: true
  ssl:
    key-store: config/certs/keystore.p12
    key-store-password: nosto
    key-store-type: pkcs12
    key-alias: spring
  error:
    include-message: never
    include-stacktrace: never
    include-exception: false

logging:
  config: classpath:logging/log4j2.xml
  level:
    root: DEBUG

management:
  metrics:
    export:
      newrelic:
        enabled: false
        api-key: 3d2212b2af6dda2e5c9e10df237b1f33FFFFNRAL
        account-id: 3519655
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

spring:
  application:
    name: "springy"
  security:
    user:
      name: admin
      password: TWr/}}H3#"2^N<C'
  output:
    ansi:
      enabled: always
  main:
    allow-bean-definition-overriding: true
  graphql:
    schema:
      printer:
        enabled: false
    graphiql:
      enabled: false

###############################################################################
