server:
  ssl:
    enabled: false
management:
  metrics:
    export:
      newrelic:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
spring:
  config:
    activate:
      on-profile: staging
logging:
  config: classpath:logging/staging_log4j2.xml
  level:
    root: ERROR

###############################################################################


