Parameters:
    App:
        Type: String
        Description: Your application's name.
    Env:
        Type: String
        Description: The environment name your service, job, or workflow is being deployed to.
    Name:
        Type: String
        Description: The name of the service, job, or workflow being deployed.

Resources:
    myDistribution:
        Type: 'AWS::CloudFront::Distribution'
        Metadata:
            'aws:copilot:description': 'Cloudfront Distribution'
        Properties:
            DistributionConfig:
                Origins:
                    - DomainName:
                          Fn::ImportValue:
                            !Sub "${App}-${Env}-PublicLoadBalancerDNS"
                      Id: myCustomOrigin
                      CustomOriginConfig:
                          HTTPPort: 80
                          OriginProtocolPolicy: http-only
                Enabled: true
                Comment: !Sub "{$App}-${Env}-${Name}"
                DefaultCacheBehavior:
                    TargetOriginId: myCustomOrigin
                    ViewerProtocolPolicy: allow-all
                    ForwardedValues:
                        QueryString: false
                        Cookies:
                            Forward: all
                ViewerCertificate:
                    CloudFrontDefaultCertificate: true
